### ISSUE TITLE
Yubikey 4 looses U2F USB type when programmed

### ISSUE THREAD

**Issue by scott-42** [Yubico/yubikey-personalization-gui#64] opened 2015-12-27 07:49 UTC
When I used the app to configure slot 1 on a Yubikey 4 it lost the U2F USB type so that it was no longer recognized by the Chrome U2F agent. Couldn't login to GitHub anymore. :(

Before:
Yubikey 4 OTP+U2F+CCID:
  Product ID:	0x0407
  Vendor ID:	0x1050
  Version:	4.26

After:
Yubikey 4 OTP+CCID:
  Product ID:	0x0405
  Vendor ID:	0x1050
  Version:	4.26

The way to get it back is to use "ykpersonalize -m6" and pretend it is a NEO device. Don't forget to unplug the device and then plug it back in.

Tested with version 3.1.23, library 1.17.2

**Comment by klali** [comment] 2015-12-28 09:19
I can't immediately reproduce this. Can you supply me with a series of steps for this? what platform did you run it on? Does it happen again for you?

**Comment by klali** [comment] 2016-10-03 11:14
Closing due to lack of information.

**Closed by klali** 2016-10-03 11:14 UTC
