### ISSUE TITLE
Static Password - Scan Code - Shift Stuck issue

### ISSUE THREAD

**Issue by Kryptonit3** [Yubico/yubikey-personalization-gui#53] opened 2015-07-30 16:29 UTC
OS: Windows 10 x64 (build 10240)
APP: YubiKey Personalization Tool 
  -  application version: 3.1.20
  -  library version: 1.17.0

YubiKey: Neo FW 3.4.3

When generating a static password on slot 2 with `Scan Code`, if the password ends in a capital letter, when using the YubiKey to generate slot 2 input, for some reason my keyboard is "Stuck" with shift. Every letter I manually type after that is capital. I was able to kick this "lock" by hitting my left shift key 5 times to prompt the sticky key window and clicking no.

Here is a video: http://youtu.be/Y28X8yA2E2U

P.S. this isn't an issue if I do `Advanced` instead of `Scan Code`. My issue with advanced is that the password it generates usually only has 2 Uppercase characters and only about 2 or so numbers and the rest is all lowercase letters and they look very similar.

Example with using Advanced: `31GUniglknrihhjbbjiclurlvrhhdrih`

Forum Link: http://forum.yubico.com/viewtopic.php?f=26&t=1985

**Comment by klali** [comment] 2015-10-13 11:18
Sorry for being slow on this.
This is not an issue with the personalization tool, but still very interesting (or maybe more interesting due to that).
I'm not able to reproduce with the password from your video. What mode are you running the Neo in? Any other details worth sharing about the setup?

**Comment by klali** [comment] 2015-10-13 11:37
So the part I missed that you had was that you where running this without APPEND_CR, reproducing now, thank you.

**Comment by klali** [comment] 2015-10-13 12:27
I'm going to close this bug since this project isn't the cause of it. This is an issue with the YubiKey NEO.
This only happens for scancode passwords that are 38 characters long and end in a capital letter when APPEND_CR is not set. So a workaround is to either use a lowercase character as the last or using a 37 character password.

**Closed by klali** 2015-10-13 12:27 UTC

**Comment by KushGoyal** [comment] 2017-06-20 06:20
This issue is resolved in yubikey 4. But all yubikey neo still have this issue. Is it possible for you guys to include this in the docs? Because it is very annoying and very hard to figure out the solution unless you find this page.

**Comment by klali** [comment] 2017-06-20 06:34
I'll investigate that. What version neo does that happen with?

**Comment by KushGoyal** [comment] 2017-06-20 06:36
I am using yubikey neo firmare version 3.4.9

**Comment by klali** [comment] 2017-06-20 08:33
Confirmed. I'll be looking into why this didn't get corrected on Neo, thanks for the heads-up.

**Comment by shanytc** [comment] 2017-12-21 22:09
I have the same issue, drives me nuts! Is there a firmware update or something available?
